// <auto-generated />
using System;
using System.Collections.Generic;
using KrakenDeploy.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KrakenDeploy.Server.Data.Migrations
{
    [DbContext(typeof(KrakenDbContext))]
    [Migration("20260504065840_AddM6Schema")]
    partial class AddM6Schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeploymentTargetTenantTag", b =>
                {
                    b.Property<Guid>("TargetsId")
                        .HasColumnType("uuid")
                        .HasColumnName("targets_id");

                    b.Property<Guid>("TenantTagsId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_tags_id");

                    b.HasKey("TargetsId", "TenantTagsId")
                        .HasName("pk_target_tenant_tags");

                    b.HasIndex("TenantTagsId")
                        .HasDatabaseName("ix_target_tenant_tags_tenant_tags_id");

                    b.ToTable("target_tenant_tags", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Deployments.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_utc");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<DateTimeOffset?>("ModifiedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_utc");

                    b.Property<int>("NextLogSequence")
                        .HasColumnType("integer")
                        .HasColumnName("next_log_sequence");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_deployments");

                    b.HasIndex("EnvironmentId")
                        .HasDatabaseName("ix_deployments_environment_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_deployments_status");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("ix_deployments_target_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_deployments_tenant_id");

                    b.HasIndex("ReleaseId", "EnvironmentId", "TargetId")
                        .HasDatabaseName("ix_deployments_release_id_environment_id_target_id");

                    b.ToTable("deployments", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Deployments.DeploymentArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CollectedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_utc");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("step_name");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("stored_path");

                    b.HasKey("Id")
                        .HasName("pk_deployment_artifacts");

                    b.HasIndex("DeploymentId")
                        .HasDatabaseName("ix_deployment_artifacts_deployment_id");

                    b.ToTable("deployment_artifacts", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Deployments.DeploymentLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_deployment_log_entries");

                    b.HasIndex("DeploymentId", "Sequence")
                        .HasDatabaseName("ix_deployment_log_entries_deployment_id_sequence");

                    b.ToTable("deployment_log_entries", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Environments.DeploymentEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<DateTimeOffset?>("ModifiedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_environments");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_environments_slug");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_environments_sort_order");

                    b.ToTable("environments", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Packages.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_name");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("package_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("stored_path");

                    b.Property<DateTimeOffset>("UploadedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_utc");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_packages");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_packages_package_id");

                    b.HasIndex("PackageId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_packages_package_id_version");

                    b.ToTable("packages", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Processes.DeploymentProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_deployment_processes");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_deployment_processes_project_id");

                    b.ToTable("deployment_processes", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Processes.DeploymentStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("package_id");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("step_type");

                    b.PrimitiveCollection<List<string>>("TargetRoles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("target_roles");

                    b.HasKey("Id")
                        .HasName("pk_deployment_steps");

                    b.HasIndex("ProcessId", "SortOrder")
                        .HasDatabaseName("ix_deployment_steps_process_id_sort_order");

                    b.ToTable("deployment_steps", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("ModifiedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_slug");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Releases.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<DateTimeOffset?>("ModifiedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_utc");

                    b.Property<string>("ProcessSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("process_snapshot");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ReleaseNotes")
                        .HasColumnType("text")
                        .HasColumnName("release_notes");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_releases");

                    b.HasIndex("ProjectId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_releases_project_id_version");

                    b.ToTable("releases", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.StepTemplates.StepTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("action_type");

                    b.Property<string>("CommunityTemplateId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("community_template_id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("description");

                    b.Property<string>("ImportedFrom")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("imported_from");

                    b.Property<DateTimeOffset?>("ModifiedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_step_templates");

                    b.HasIndex("ActionType")
                        .HasDatabaseName("ix_step_templates_action_type");

                    b.HasIndex("CommunityTemplateId")
                        .HasDatabaseName("ix_step_templates_community_template_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_step_templates_name");

                    b.ToTable("step_templates", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Targets.DeploymentTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_version");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<DateTimeOffset?>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_utc");

                    b.Property<string>("MachineName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("machine_name");

                    b.Property<DateTimeOffset?>("ModifiedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("operating_system");

                    b.Property<string>("RegistrationKeyHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("registration_key_hash");

                    b.Property<DateTimeOffset?>("RegistrationTokenExpiresUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_token_expires_utc");

                    b.PrimitiveCollection<List<string>>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("roles");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TransportMode")
                        .HasColumnType("integer")
                        .HasColumnName("transport_mode");

                    b.HasKey("Id")
                        .HasName("pk_deployment_targets");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_deployment_targets_status");

                    b.ToTable("deployment_targets", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Tenants.TagSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("ModifiedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tag_sets");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_sets_tenant_id_name");

                    b.ToTable("tag_sets", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("ModifiedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<Guid?>("VariableSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("variable_set_id");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Tenants.TenantTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<DateTimeOffset?>("ModifiedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TagSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_set_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_tags");

                    b.HasIndex("TagSetId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_tags_tag_set_id_name");

                    b.ToTable("tenant_tags", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Variables.Variable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scope");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_variables");

                    b.HasIndex("SetId", "Name")
                        .HasDatabaseName("ix_variables_set_id_name");

                    b.ToTable("variables", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Variables.VariableSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_variable_sets");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_variable_sets_project_id");

                    b.ToTable("variable_sets", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.Server.Data.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("ProjectTenant", b =>
                {
                    b.Property<Guid>("ProjectsId")
                        .HasColumnType("uuid")
                        .HasColumnName("projects_id");

                    b.Property<Guid>("TenantsId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenants_id");

                    b.HasKey("ProjectsId", "TenantsId")
                        .HasName("pk_project_tenants");

                    b.HasIndex("TenantsId")
                        .HasDatabaseName("ix_project_tenants_tenants_id");

                    b.ToTable("project_tenants", (string)null);
                });

            modelBuilder.Entity("DeploymentTargetTenantTag", b =>
                {
                    b.HasOne("KrakenDeploy.Server.Core.Domain.Targets.DeploymentTarget", null)
                        .WithMany()
                        .HasForeignKey("TargetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_target_tenant_tags_deployment_targets_targets_id");

                    b.HasOne("KrakenDeploy.Server.Core.Domain.Tenants.TenantTag", null)
                        .WithMany()
                        .HasForeignKey("TenantTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_target_tenant_tags_tenant_tags_tenant_tags_id");
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Deployments.Deployment", b =>
                {
                    b.HasOne("KrakenDeploy.Server.Core.Domain.Environments.DeploymentEnvironment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deployments_environments_environment_id");

                    b.HasOne("KrakenDeploy.Server.Core.Domain.Releases.Release", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deployments_releases_release_id");

                    b.HasOne("KrakenDeploy.Server.Core.Domain.Targets.DeploymentTarget", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_deployments_deployment_targets_target_id");

                    b.HasOne("KrakenDeploy.Server.Core.Domain.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_deployments_tenants_tenant_id");

                    b.Navigation("Environment");

                    b.Navigation("Release");

                    b.Navigation("Target");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Deployments.DeploymentArtifact", b =>
                {
                    b.HasOne("KrakenDeploy.Server.Core.Domain.Deployments.Deployment", "Deployment")
                        .WithMany("Artifacts")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_artifacts_deployments_deployment_id");

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Deployments.DeploymentLogEntry", b =>
                {
                    b.HasOne("KrakenDeploy.Server.Core.Domain.Deployments.Deployment", "Deployment")
                        .WithMany("LogEntries")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_log_entries_deployments_deployment_id");

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Processes.DeploymentProcess", b =>
                {
                    b.HasOne("KrakenDeploy.Server.Core.Domain.Projects.Project", "Project")
                        .WithOne("Process")
                        .HasForeignKey("KrakenDeploy.Server.Core.Domain.Processes.DeploymentProcess", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_processes_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Processes.DeploymentStep", b =>
                {
                    b.HasOne("KrakenDeploy.Server.Core.Domain.Processes.DeploymentProcess", "Process")
                        .WithMany("Steps")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_steps_deployment_processes_process_id");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Releases.Release", b =>
                {
                    b.HasOne("KrakenDeploy.Server.Core.Domain.Projects.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_releases_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Tenants.TagSet", b =>
                {
                    b.HasOne("KrakenDeploy.Server.Core.Domain.Tenants.Tenant", "Tenant")
                        .WithMany("TagSets")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_sets_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Tenants.TenantTag", b =>
                {
                    b.HasOne("KrakenDeploy.Server.Core.Domain.Tenants.TagSet", "TagSet")
                        .WithMany("Tags")
                        .HasForeignKey("TagSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_tags_tag_sets_tag_set_id");

                    b.Navigation("TagSet");
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Variables.Variable", b =>
                {
                    b.HasOne("KrakenDeploy.Server.Core.Domain.Variables.VariableSet", "Set")
                        .WithMany("Variables")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_variables_variable_sets_set_id");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Variables.VariableSet", b =>
                {
                    b.HasOne("KrakenDeploy.Server.Core.Domain.Projects.Project", "Project")
                        .WithOne("VariableSet")
                        .HasForeignKey("KrakenDeploy.Server.Core.Domain.Variables.VariableSet", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_variable_sets_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("KrakenDeploy.Server.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("KrakenDeploy.Server.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("KrakenDeploy.Server.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("KrakenDeploy.Server.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("ProjectTenant", b =>
                {
                    b.HasOne("KrakenDeploy.Server.Core.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_tenants_projects_projects_id");

                    b.HasOne("KrakenDeploy.Server.Core.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_tenants_tenants_tenants_id");
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Deployments.Deployment", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Processes.DeploymentProcess", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Projects.Project", b =>
                {
                    b.Navigation("Process");

                    b.Navigation("VariableSet");
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Tenants.TagSet", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Tenants.Tenant", b =>
                {
                    b.Navigation("TagSets");
                });

            modelBuilder.Entity("KrakenDeploy.Server.Core.Domain.Variables.VariableSet", b =>
                {
                    b.Navigation("Variables");
                });
#pragma warning restore 612, 618
        }
    }
}
