<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <KrakenStepPackageId>octopus.substitutevariables</KrakenStepPackageId>
    <KrakenStepPackageVersion>1.0.0</KrakenStepPackageVersion>
    <KrakenStepPackageDisplayName>Substitute Variables in Files</KrakenStepPackageDisplayName>
    <KrakenStepPackageStepTypes>Octopus.SubstituteVariables</KrakenStepPackageStepTypes>
    <KrakenStepPackageExecutorTypeName>KrakenDeploy.Steps.SubstituteVariables.SubstituteVariablesStepHandler</KrakenStepPackageExecutorTypeName>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Octostache" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\KrakenDeploy.Contracts\KrakenDeploy.Contracts.csproj" />
  </ItemGroup>

  <Import Project="..\KrakenStepPackage.targets" />

</Project>
