using System.Diagnostics;
using System.Runtime.InteropServices;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace KrakenDeploy.Steps.Common;

/// <summary>
/// Runs a script in a child process, capturing stdout and stderr line-by-line
/// and forwarding them to the caller via a callback. Supported syntaxes:
/// PowerShell (Desktop or Core), Bash, CSharp (dotnet-script), FSharp (dotnet fsi),
/// Python.
/// <para>
/// Shared across every step package that needs to shell out to a script
/// runtime — currently <c>kraken.script</c>, <c>kraken.iis</c> (PowerShell
/// generated by <c>IisScriptGenerator</c>), and <c>octopus.windowsservice</c>
/// (PowerShell generated by <c>WindowsServiceScriptGenerator</c>). The
/// canonical home converged here in Phase D-8.6 when the last agent-side
/// in-DI consumer was retired.
/// </para>
/// </summary>
public sealed class ScriptRunner
{
    private readonly ILogger _logger;

    /// <summary>
    /// Constructs the runner with a logger; if step packages can't resolve
    /// ILogger&lt;ScriptRunner&gt; through the host's DI (they don't see it),
    /// callers pass <see cref="NullLogger.Instance"/> or build a logger via
    /// the agent's ILoggerFactory at construction time.
    /// </summary>
    public ScriptRunner(ILogger? logger = null)
        => _logger = logger ?? NullLogger.Instance;

    /// <summary>
    /// Executes the script and returns <c>true</c> if the process exited with code 0.
    /// </summary>
    public async Task<bool> RunAsync(
        string scriptBody,
        string syntax,
        string workingDirectory,
        IReadOnlyDictionary<string, string> environmentVariables,
        Func<string, string, Task> onOutput,
        CancellationToken ct,
        string? powerShellEdition = null)
    {
        var exit = await RunAndReturnExitCodeAsync(
            scriptBody, syntax, workingDirectory,
            environmentVariables, onOutput, ct, powerShellEdition).ConfigureAwait(false);
        return exit == 0;
    }

    /// <summary>
    /// M11.E.7 — same as <see cref="RunAsync"/> but returns the process exit
    /// code rather than collapsing it to a bool. The ad-hoc-action executor
    /// needs the raw code in its per-target result so the iteration-verdict
    /// LLM can reason about specific exit values (non-zero from a Get-* probe
    /// is treated differently from a service-restart failure).
    /// </summary>
    public async Task<int> RunAndReturnExitCodeAsync(
        string scriptBody,
        string syntax,
        string workingDirectory,
        IReadOnlyDictionary<string, string> environmentVariables,
        Func<string, string, Task> onOutput,
        CancellationToken ct,
        string? powerShellEdition = null)
    {
        var scriptFile = WriteScriptFile(scriptBody, syntax);
        try
        {
            return await ExecuteAsync(scriptFile, syntax, powerShellEdition, workingDirectory,
                environmentVariables, onOutput, ct).ConfigureAwait(false);
        }
        finally
        {
            TryDelete(scriptFile);
        }
    }

    private static string WriteScriptFile(string body, string syntax)
    {
        var ext = syntax.ToLowerInvariant() switch
        {
            "bash"   => ".sh",
            "csharp" => ".csx",
            "fsharp" => ".fsx",
            "python" => ".py",
            _        => ".ps1",
        };
        var path = Path.Combine(Path.GetTempPath(), $"kraken-{Guid.NewGuid():N}{ext}");
        File.WriteAllText(path, body);
        return path;
    }

    private async Task<int> ExecuteAsync(
        string scriptFile,
        string syntax,
        string? powerShellEdition,
        string workingDirectory,
        IReadOnlyDictionary<string, string> envVars,
        Func<string, string, Task> onOutput,
        CancellationToken ct)
    {
        var (exe, args) = BuildCommand(scriptFile, syntax, powerShellEdition);

        var psi = new ProcessStartInfo
        {
            FileName               = exe,
            Arguments              = args,
            WorkingDirectory       = workingDirectory,
            UseShellExecute        = false,
            RedirectStandardOutput = true,
            RedirectStandardError  = true,
            CreateNoWindow         = true,
        };

        foreach (var (k, v) in envVars)
        {
            psi.Environment[k] = v;
        }

        using var process = new Process { StartInfo = psi, EnableRaisingEvents = true };

        // stdout and stderr callbacks fire on DIFFERENT threadpool threads —
        // List<T>.Add is not thread-safe, so both the adds and the final
        // snapshot take the gate (same defect class B4 fixed in the server-side
        // runner).
        var outputTasks = new List<Task>();
        var outputGate = new Lock();

        process.OutputDataReceived += (_, e) =>
        {
            if (e.Data is not null)
            {
                lock (outputGate) { outputTasks.Add(onOutput("info", e.Data)); }
            }
        };
        process.ErrorDataReceived += (_, e) =>
        {
            if (e.Data is not null)
            {
                lock (outputGate) { outputTasks.Add(onOutput("error", e.Data)); }
            }
        };

        _logger.LogDebug("Starting script process: {Exe} {Args}", exe, args);
        process.Start();
        process.BeginOutputReadLine();
        process.BeginErrorReadLine();

        try
        {
            await process.WaitForExitAsync(ct).ConfigureAwait(false);
        }
        catch (OperationCanceledException)
        {
            // B6 (cancel push) + per-step timeout: WaitForExitAsync(ct) only
            // stops WAITING — the child and everything it spawned keep running,
            // which leaked orphan process trees on every cancel/timeout. Kill
            // the whole tree, reap briefly so the handle isn't abandoned
            // mid-exit, then let the cancellation propagate.
            try
            {
                process.Kill(entireProcessTree: true);
                _logger.LogWarning("Script process tree killed (cancelled or timed out).");
            }
            catch (InvalidOperationException)
            {
                // Already exited between the cancellation and the kill.
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to kill the script process tree.");
            }
            try
            {
                using var reap = new CancellationTokenSource(TimeSpan.FromSeconds(10));
                await process.WaitForExitAsync(reap.Token).ConfigureAwait(false);
            }
            catch (OperationCanceledException)
            {
                _logger.LogWarning("Script process did not exit within 10 s of the kill.");
            }
            throw;
        }

        Task[] pendingOutput;
        lock (outputGate) { pendingOutput = outputTasks.ToArray(); }
        await Task.WhenAll(pendingOutput).ConfigureAwait(false);

        var exitCode = process.ExitCode;
        _logger.LogDebug("Script exited with code {ExitCode}.", exitCode);
        return exitCode;
    }

    private static (string exe, string args) BuildCommand(
        string scriptFile, string syntax, string? powerShellEdition)
    {
        switch (syntax.ToLowerInvariant())
        {
            case "bash":
                return ("bash", $"\"{scriptFile}\"");

            case "csharp":
                // dotnet-script must be installed as a global tool:
                //   dotnet tool install -g dotnet-script
                return ("dotnet", $"script \"{scriptFile}\"");

            case "fsharp":
                return ("dotnet", $"fsi \"{scriptFile}\"");

            case "python":
                return ("python", $"\"{scriptFile}\"");

            default:
                // PowerShell — pick the executable by edition.
                var wantDesktop = "Desktop".Equals(
                    powerShellEdition, StringComparison.OrdinalIgnoreCase);

                if (wantDesktop && RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                {
                    return ("powershell.exe",
                        $"-NonInteractive -NoProfile -ExecutionPolicy Bypass -File \"{scriptFile}\"");
                }

                return ("pwsh", $"-NonInteractive -NoProfile -File \"{scriptFile}\"");
        }
    }

    private static void TryDelete(string path)
    {
        try { File.Delete(path); } catch { /* best effort */ }
    }
}
