// <auto-generated />
using System;
using KrakenDeploy.Platform;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KrakenDeploy.Platform.Migrations
{
    [DbContext(typeof(PlatformReleaseDbContext))]
    [Migration("20260827081000_InitialPlatform")]
    partial class InitialPlatform
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KrakenDeploy.Platform.Releases.AppRelease", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DeployedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deployed_at_utc");

                    b.Property<DateTimeOffset?>("DrainDeadlineUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("drain_deadline_utc");

                    b.Property<DateTimeOffset?>("DrainedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("drained_at_utc");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<short>("SlotNo")
                        .HasColumnType("smallint")
                        .HasColumnName("slot_no");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_app_releases");

                    b.HasIndex("SlotNo")
                        .IsUnique()
                        .HasDatabaseName("ux_app_releases_slot_no_live")
                        .HasFilter("status <> 3");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_app_releases_status");

                    b.ToTable("app_releases", "platform");
                });

            modelBuilder.Entity("KrakenDeploy.Platform.Releases.PlatformSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_platform_settings");

                    b.ToTable("platform_settings", "platform");
                });
#pragma warning restore 612, 618
        }
    }
}
