// <auto-generated />
using System;
using KrakenDeploy.ControlPlane.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KrakenDeploy.ControlPlane.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KrakenDeploy.ControlPlane.Catalog.BusinessAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConnSecretRef")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("conn_secret_ref");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_utc");

                    b.Property<Guid>("ShardId")
                        .HasColumnType("uuid")
                        .HasColumnName("shard_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("subdomain");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.HasKey("Id")
                        .HasName("pk_business_accounts");

                    b.HasIndex("ShardId")
                        .HasDatabaseName("ix_business_accounts_shard_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_business_accounts_status");

                    b.HasIndex("Subdomain")
                        .IsUnique()
                        .HasDatabaseName("ix_business_accounts_subdomain");

                    b.ToTable("business_accounts", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.ControlPlane.Catalog.Shard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("HostSecretRef")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("host_secret_ref");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_shards");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_shards_status");

                    b.ToTable("shards", (string)null);
                });

            modelBuilder.Entity("KrakenDeploy.ControlPlane.Catalog.BusinessAccount", b =>
                {
                    b.HasOne("KrakenDeploy.ControlPlane.Catalog.Shard", "Shard")
                        .WithMany("Accounts")
                        .HasForeignKey("ShardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_business_accounts_shards_shard_id");

                    b.Navigation("Shard");
                });

            modelBuilder.Entity("KrakenDeploy.ControlPlane.Catalog.Shard", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
